<?php

namespace TrackerBundle\Repository;

/**
 * WorkDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkDayRepository extends \Doctrine\ORM\EntityRepository
{
}
